name = "DONEs"
uuid = "461570c0-f3f8-11e9-144c-6d5dea563121"
authors = ["Reinier Doelman"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
